name = "KernelAbstractionsSmooth"
uuid = "d022130c-3d6e-4958-b47b-f1b74eaf3f31"
authors = ["Joonas Miettinen <joonas.m.miettinen@gmail.com>"]
version = "0.1.0"

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[compat]
KernelAbstractions = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
